name: Build SunamoCollectionsGeneric

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoCollectionsGeneric
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoCollectionsGeneric/SunamoCollectionsGeneric.csproj

    - name: Build
      run: dotnet build SunamoCollectionsGeneric/SunamoCollectionsGeneric.csproj --configuration Release --no-restore

  test:
    name: Test SunamoCollectionsGeneric.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoCollectionsGeneric.Tests/SunamoCollectionsGeneric.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoCollectionsGeneric.Tests/SunamoCollectionsGeneric.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoCollectionsGeneric.Tests/SunamoCollectionsGeneric.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
